#+title: Creating a Questionnaire using cl-sbt/questionnaire Macros in a Web Application
#+author: Marcus Kammer
#+email: marcus.kammer@mailbox.org
#+date: [2023-09-14 Thu]

* Introduction

Questionnaires are powerful tools for gathering information and insights from
users. They are crucial for understanding user behaviors, preferences, and
requirements. This document will demonstrate how to build a web-based
questionnaire using the cl-sbt/questionnaire macros in a Common Lisp
application.

** The Importance of Questionnaires

Questionnaires help in collecting data for various purposes including market
research, user experience study, and many more. They can be in multiple formats
like single-choice, multiple-choice, or open-ended questions.

*** Types of Questions

- Single Choice: Questions that allow one answer.
- Multiple Choice: Questions that allow multiple answers.
- Text: Open-ended questions for free text input.

* Integrating cl-sbt/questionnaire Macros

To create a questionnaire in your Common Lisp web application,
cl-sbt/questionnaire macros can be employed. These macros generate the HTML
required for different types of questions in a questionnaire.

#+begin_src lisp :results none
  (defpackage feat-questionnaire
    (:use :cl)
    (:import-from
     :cl-sbt
     :with-page
     :write-html-to-file)
    (:import-from
     :cl-sbt/grid
     :con)
    (:import-from
     :cl-sbt/questionnaire
     :questionnaire))

  (in-package :feat-questionnaire)

  (write-html-to-file "questionnaire.html"
                      (spinneret:with-html-string
                        (with-page (:author "Marcus Kammer" :pagetitle "Questionnaire Example")
                          (con ()
                            (questionnaire "/submit"
                                           (:ask "How old are you?"
                                            :group "age"
                                            :choices (:single "18-24" "25-34" "35-44" "45-54" "55+"))
                                           (:ask "Your Gender?"
                                            :group "gender"
                                            :choices (:single "Male" "Female" "Non-Binary" "Prefer not to say"))
                                           (:ask "How many hours per day, on average, do you spend browsing the internet?"
                                            :group "internet"
                                            :choices (:single "Less than 1 hour" "1-3 hours" "3-5 hours" "5+ hours"))
                                           (:ask "Which of the following devices do you regularly use to browse the internet? (Select all that apply)"
                                            :group "devices"
                                            :choices (:multiple
                                                      "Desktop"
                                                      "Laptop"
                                                      "Tablet"
                                                      "Smartphone"
                                                      :text
                                                      "Others (please specify):"))
                                           (:ask "Which social media platforms do you use regularly? (Select all that apply)"
                                            :group "socialmedia"
                                            :choices (:multiple
                                                      "Facebook"
                                                      "Twitter"
                                                      "Instagram"
                                                      "LinkedIn"
                                                      "TikTok"
                                                      "Snapchat"
                                                      "Pinterest"
                                                      "Youtube"
                                                      :text
                                                      "Others (please specify):")))))))
#+end_src
